name: Elixir CI

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build release
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        elixir-version: '1.18'
        
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Install dependencies
      run: mix deps.get
      
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt install libasound2-dev
            
    - name: Build release
      env:
        MIX_ENV: prod
        RUSTLER_PRECOMPILED_FORCE_BUILD_ALL: true
      run: mix release
      
    - name: ls
      run: |
        ls _build/prod/rel
        
    - name: Get artifacts (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir release
        tar -cjf release/eos_midi_controller_${{runner.os}}.tar.bz2 _build/prod/rel/eos_midi_controller
            
    - name: Get artifacts (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir release
        7z a -tzip release/eos_midi_controller_${{runner.os}}.zip _build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: eos_midi_controller_${{ runner.os }}
        path: ${{github.workspace}}/_build/prod/rel/eos_midi_controller

    - name: GH Release
      if: startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v0.1.13
      with:
        # Newline-delimited list of path globs for asset files to upload
        files: ${{github.workspace}}/release/*
